language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - docker

cache:
  - pip

install:
  - pip install -r requirements.txt
  - pip install pylint pycodestyle  # requirements only for CI
  - docker build -t imap2smtp:latest -f docker/Dockerfile .

script:
  - pylint --rcfile=.pylintrc imap2smtp.py docker/entrypoint.py
  - pycodestyle imap2smtp.py docker/entrypoint.py
  # - python -m unittest discover tests -v
  # - docker run --rm -it --entrypoint python imap2smtp:latest -m unittest discover tests -v
