name: main
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup tests
      run: |
        pip install -r requirements.txt
        pip install pylama
    - name: Run tests
      run: |
        pylama -v imap2smtp.py docker/entrypoint.py
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: selfhostingtools/imap2smtp
        tags: latest
    - uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: selfhosting-tools/imap2smtp/imap2smtp
        tags: latest
